# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12842b46f9889a5e99d0ddb1f2e6da63786b5e8cf15c6e2ca523a4159ddba88418c1f88d8463a1301af86e369e1167155ac0f3ab64ec3644e19274ca1b23c47b

test:
  secret_key_base: 2c6fe4083b54e64a49f7edee8efe14d78c5e778a635c7e284b5653a064080439e6e8c9590081ba2a79ec3b5614d8cb24d5cca137d0e07a50f4aa2d53bd14bd39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
